version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:11.2
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP
  # app:
  #   image: linkace/linkace:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./.env:/app/.env
  #     - ./backups:/app/storage/app/backups
  #     - linkace_app:/app
  #     - linkace_logs:/app/storage/logs

  # --- PHP
  app:
    build:
      context: .
      dockerfile: ./resources/docker/dockerfiles/development.Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app:delegated
      - ./resources/docker/php/php-dev.ini:/usr/local/etc/php/conf.d/php.ini:ro

  # --- nginx
  nginx:
    image: bitnami/nginx:1.24
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:8080"
      - "0.0.0.0:443:8443"
    depends_on:
      - app
    volumes:
      - linkace_app:/app
      # Replace `nginx.conf` with `nginx-ssl.conf` and remove the hash from the following line
      # if you want to use HTTPS for this container
      - ./nginx-ssl.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro
      - ../ssl/:/certs:ro

  # --- Redis
  redis:
    image: bitnami/redis:7.2
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  linkace_app:
  linkace_logs:
  db:
    driver: local
